import { useMemo, useState } from "react";
import { BarChart3, Brain, Heart, Activity, Filter, ListChecks, ChevronLeft, ChevronRight, Download } from "lucide-react";
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { useData } from "@/contexts/DataContext";
import { useLocalStorage } from "@/hooks/useLocalStorage";

function getShortDate(s: string) { return new Date(s + "T00:00:00").toLocaleDateString("en-US", { month: "short", day: "numeric" }); }

function getMonthKey(d: Date) { return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`; }
function getMonthLabel(key: string) {
  const [y, m] = key.split("-");
  return new Date(Number(y), Number(m) - 1).toLocaleDateString("en-US", { month: "long", year: "numeric" });
}

function getDatesInRange(start: Date, end: Date): string[] {
  const dates: string[] = [];
  const cur = new Date(start);
  while (cur <= end) {
    dates.push(cur.toISOString().split("T")[0]);
    cur.setDate(cur.getDate() + 1);
  }
  return dates;
}

function getWeekRange(): { start: Date; end: Date } {
  const now = new Date(); const day = now.getDay();
  const start = new Date(now); start.setDate(now.getDate() - day);
  const end = new Date(start); end.setDate(start.getDate() + 6);
  return { start, end };
}

function getMonthRange(monthKey: string): { start: Date; end: Date } {
  const [y, m] = monthKey.split("-").map(Number);
  const start = new Date(y, m - 1, 1);
  const end = new Date(y, m, 0);
  return { start, end };
}

interface OutcomeItem { task: string; outcome: string; system: string; mission: string; completed: boolean; date: string; }

const ChartTooltip = ({ active, payload, label }: { active?: boolean; payload?: Array<{ value: number; name: string; color: string }>; label?: string }) => {
  if (!active || !payload?.length) return null;
  return (
    <div className="bg-zinc-900 border border-zinc-700 rounded-lg p-3 text-xs shadow-xl">
      <p className="text-zinc-300 mb-1.5 font-medium">{label}</p>
      {payload.map((p, i) => <p key={i} style={{ color: p.color }}>{p.name}: <span className="font-semibold">{p.value}</span></p>)}
    </div>
  );
};

function mentalLabel(v: number) { return v === 1 ? "Low" : v === 2 ? "Medium" : "High"; }

function generateInsightsMd(
  mode: string,
  label: string,
  chartData: Array<{ date: string; label: string; tasksCompleted: number; mentalAvg: number; physical: number }>,
  outcomes: OutcomeItem[],
  stats: { totalTasks: number; avgMental: string; healthyDays: number; totalDays: number }
): string {
  const lines: string[] = [];
  lines.push(`# ${mode === "weekly" ? "Weekly" : "Monthly"} Insights — ${label}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Tasks | ${stats.totalTasks} |`);
  lines.push(`| Avg Mental Score | ${stats.avgMental}/3 |`);
  lines.push(`| Healthy Days | ${stats.healthyDays}/${stats.totalDays} |`);
  lines.push("");
  lines.push("## Daily Breakdown");
  lines.push("");
  lines.push(`| Date | Tasks | Mental | Physical |`);
  lines.push(`|------|-------|--------|----------|`);
  for (const d of chartData) {
    const phys = d.physical === 3 ? "Good" : d.physical === 2 ? "Sick" : d.physical === 1 ? "Critical" : "—";
    lines.push(`| ${d.label} | ${d.tasksCompleted} | ${d.mentalAvg > 0 ? d.mentalAvg.toFixed(1) : "—"} | ${phys} |`);
  }
  lines.push("");
  if (outcomes.length > 0) {
    lines.push("## Outcomes");
    lines.push("");
    for (const o of outcomes) {
      const check = o.completed ? "x" : " ";
      lines.push(`- [${check}] **${o.task || "Untitled"}** (${getShortDate(o.date)})`);
      if (o.outcome) lines.push(`  - Outcome: ${o.outcome}`);
      if (o.system) lines.push(`  - System: ${o.system}`);
      if (o.mission) lines.push(`  - Mission: ${o.mission}`);
    }
    lines.push("");
  }
  lines.push("---");
  lines.push(`_Generated by Daily Tracker on ${new Date().toLocaleString()}_`);
  return lines.join("\n");
}

function downloadMd(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function InsightsPage() {
  const { entries } = useData();
  const [mode, setMode] = useLocalStorage<"weekly" | "monthly">("insights-mode", "weekly");
  const [monthOffset, setMonthOffset] = useState(0);
  const [filterSystem, setFilterSystem] = useState("");
  const [filterMission, setFilterMission] = useState("");

  // Determine available months
  const availableMonths = useMemo(() => {
    const months = new Set<string>();
    const now = new Date();
    months.add(getMonthKey(now));
    for (const dateStr of Object.keys(entries)) {
      months.add(dateStr.substring(0, 7));
    }
    return Array.from(months).sort().reverse();
  }, [entries]);

  const currentMonthKey = availableMonths[Math.min(monthOffset, availableMonths.length - 1)] || getMonthKey(new Date());

  // Build chart data and outcomes
  const { chartData, outcomes, stats } = useMemo(() => {
    const range = mode === "weekly" ? getWeekRange() : getMonthRange(currentMonthKey);
    const dates = getDatesInRange(range.start, range.end);
    const chart: Array<{ date: string; label: string; tasksCompleted: number; totalTasks: number; mentalAvg: number; physical: number }> = [];
    const outs: OutcomeItem[] = [];

    for (const dateStr of dates) {
      const entry = entries[dateStr];
      const mentalAvg = entry ? (entry.mentalStatus.morning + entry.mentalStatus.afternoon + entry.mentalStatus.night) / 3 : 0;
      const physVal = entry?.physicalStatus === "good" ? 3 : entry?.physicalStatus === "sick" ? 2 : entry?.physicalStatus === "critical" ? 1 : 0;
      const completed = entry ? entry.tasks.filter((t) => t.completed).length : 0;
      chart.push({ date: dateStr, label: getShortDate(dateStr), tasksCompleted: completed, totalTasks: entry?.tasks.length || 0, mentalAvg: Math.round(mentalAvg * 10) / 10, physical: physVal });

      if (entry) {
        for (const t of entry.tasks) {
          if (t.outcome.trim() || t.task.trim()) {
            outs.push({ task: t.task, outcome: t.outcome, system: t.system, mission: t.mission, completed: t.completed, date: dateStr });
          }
        }
      }
    }

    const daysWithData = chart.filter((d) => d.mentalAvg > 0);
    const totalTasks = chart.reduce((s, d) => s + d.tasksCompleted, 0);
    const avgMental = daysWithData.length > 0 ? (daysWithData.reduce((s, d) => s + d.mentalAvg, 0) / daysWithData.length).toFixed(1) : "0";
    const healthyDays = chart.filter((d) => d.physical === 3).length;

    return { chartData: chart, outcomes: outs, stats: { totalTasks, avgMental, healthyDays, totalDays: dates.length } };
  }, [entries, mode, currentMonthKey]);

  // Collect unique systems and missions for filter
  const allSystems = useMemo(() => [...new Set(outcomes.map((o) => o.system).filter(Boolean))], [outcomes]);
  const allMissions = useMemo(() => [...new Set(outcomes.map((o) => o.mission).filter(Boolean))], [outcomes]);

  const filteredOutcomes = useMemo(() => {
    return outcomes.filter((o) => {
      if (filterSystem && o.system !== filterSystem) return false;
      if (filterMission && o.mission !== filterMission) return false;
      return true;
    });
  }, [outcomes, filterSystem, filterMission]);

  const hasData = Object.keys(entries).length > 0;

  return (
    <div className="fade-in space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-zinc-100 tracking-tight">Insights</h2>
          <p className="text-sm text-zinc-400 mt-0.5">Visualize your patterns and progress</p>
        </div>
        <div className="flex items-center gap-3">
          <Button variant="outline" size="sm" onClick={() => {
            const label = mode === "weekly" ? "Current Week" : getMonthLabel(currentMonthKey);
            const md = generateInsightsMd(mode, label, chartData, outcomes, stats);
            const filename = mode === "weekly" ? `insights-weekly-${new Date().toISOString().split("T")[0]}.md` : `insights-${currentMonthKey}.md`;
            downloadMd(md, filename);
          }} className="gap-1.5 text-xs h-8 border-zinc-700 text-zinc-300 hover:text-white">
            <Download className="w-3.5 h-3.5" />Export .md
          </Button>
          {mode === "monthly" && (
            <div className="flex items-center gap-1">
              <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => setMonthOffset(Math.min(monthOffset + 1, availableMonths.length - 1))}><ChevronLeft className="w-4 h-4" /></Button>
              <span className="text-sm text-zinc-300 min-w-[140px] text-center font-medium">{getMonthLabel(currentMonthKey)}</span>
              <Button variant="ghost" size="icon" className="h-8 w-8" disabled={monthOffset <= 0} onClick={() => setMonthOffset(Math.max(monthOffset - 1, 0))}><ChevronRight className="w-4 h-4" /></Button>
            </div>
          )}
          <Tabs value={mode} onValueChange={(v) => { setMode(v as "weekly" | "monthly"); setMonthOffset(0); }}>
            <TabsList><TabsTrigger value="weekly">Weekly</TabsTrigger><TabsTrigger value="monthly">Monthly</TabsTrigger></TabsList>
          </Tabs>
        </div>
      </div>

      {!hasData ? (
        <Card className="glow-blue-subtle"><CardContent className="flex flex-col items-center justify-center py-16">
          <div className="w-16 h-16 rounded-2xl bg-blue-500/10 flex items-center justify-center mb-4"><BarChart3 className="w-8 h-8 text-blue-400" /></div>
          <h3 className="text-lg font-semibold text-zinc-100 mb-2">No Data Yet</h3>
          <p className="text-sm text-zinc-400 text-center max-w-sm">Start tracking in the Journal to see insights here.</p>
        </CardContent></Card>
      ) : (<>
        {/* Mental Health */}
        <Card className="glow-blue-subtle">
          <CardHeader><CardTitle className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-purple-500/10 flex items-center justify-center"><Brain className="w-4 h-4 text-purple-400" /></div>
            <span className="text-zinc-100">Mental Health Trend</span>
          </CardTitle></CardHeader>
          <CardContent><div className="chart-container">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={chartData}>
                <defs><linearGradient id="mentalG" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#8b5cf6" stopOpacity={0.3} /><stop offset="95%" stopColor="#8b5cf6" stopOpacity={0} /></linearGradient></defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#2a2a3e" />
                <XAxis dataKey="label" stroke="#64748b" fontSize={11} tickLine={false} axisLine={false} />
                <YAxis domain={[0, 3]} stroke="#64748b" fontSize={11} tickLine={false} axisLine={false} ticks={[1, 2, 3]} />
                <Tooltip content={<ChartTooltip />} />
                <Area type="monotone" dataKey="mentalAvg" name="Mental" stroke="#8b5cf6" strokeWidth={2.5} fill="url(#mentalG)" dot={{ fill: "#8b5cf6", strokeWidth: 0, r: 3 }} activeDot={{ r: 5, fill: "#8b5cf6", stroke: "#fff", strokeWidth: 2 }} />
              </AreaChart>
            </ResponsiveContainer>
          </div></CardContent>
        </Card>

        {/* Physical Health */}
        <Card className="glow-blue-subtle">
          <CardHeader><CardTitle className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-emerald-500/10 flex items-center justify-center"><Heart className="w-4 h-4 text-emerald-400" /></div>
            <span className="text-zinc-100">Physical Health Trend</span>
          </CardTitle></CardHeader>
          <CardContent><div className="chart-container">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={chartData}>
                <defs><linearGradient id="physG" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#10b981" stopOpacity={0.3} /><stop offset="95%" stopColor="#10b981" stopOpacity={0} /></linearGradient></defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#2a2a3e" />
                <XAxis dataKey="label" stroke="#64748b" fontSize={11} tickLine={false} axisLine={false} />
                <YAxis domain={[0, 3]} stroke="#64748b" fontSize={11} tickLine={false} axisLine={false} ticks={[1, 2, 3]} tickFormatter={(v: number) => v === 3 ? "Good" : v === 2 ? "Sick" : v === 1 ? "Critical" : ""} />
                <Tooltip content={<ChartTooltip />} />
                <Area type="stepAfter" dataKey="physical" name="Physical" stroke="#10b981" strokeWidth={2.5} fill="url(#physG)" dot={{ fill: "#10b981", strokeWidth: 0, r: 3 }} activeDot={{ r: 5, fill: "#10b981", stroke: "#fff", strokeWidth: 2 }} />
              </AreaChart>
            </ResponsiveContainer>
          </div></CardContent>
        </Card>

        {/* Stats */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <Card><CardContent className="p-5 flex items-center gap-4">
            <div className="w-12 h-12 rounded-xl bg-blue-500/10 flex items-center justify-center"><Activity className="w-6 h-6 text-blue-400" /></div>
            <div><p className="text-2xl font-bold text-zinc-100">{stats.totalTasks}</p><p className="text-xs text-zinc-400">Total Tasks</p></div>
          </CardContent></Card>
          <Card><CardContent className="p-5 flex items-center gap-4">
            <div className="w-12 h-12 rounded-xl bg-purple-500/10 flex items-center justify-center"><Brain className="w-6 h-6 text-purple-400" /></div>
            <div><p className="text-2xl font-bold text-zinc-100">{stats.avgMental}</p><p className="text-xs text-zinc-400">Avg Mental Score</p></div>
          </CardContent></Card>
          <Card><CardContent className="p-5 flex items-center gap-4">
            <div className="w-12 h-12 rounded-xl bg-emerald-500/10 flex items-center justify-center"><Heart className="w-6 h-6 text-emerald-400" /></div>
            <div><p className="text-2xl font-bold text-zinc-100">{stats.healthyDays}/{stats.totalDays}</p><p className="text-xs text-zinc-400">Healthy Days</p></div>
          </CardContent></Card>
        </div>

        {/* Outcome List */}
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between flex-wrap gap-3">
              <CardTitle className="flex items-center gap-2.5">
                <div className="w-7 h-7 rounded-lg bg-amber-500/10 flex items-center justify-center"><ListChecks className="w-4 h-4 text-amber-400" /></div>
                <span className="text-zinc-100">Outcomes</span>
                <span className="text-xs text-zinc-500 font-normal ml-1">{filteredOutcomes.length} items</span>
              </CardTitle>
              <div className="flex items-center gap-2">
                <Filter className="w-3.5 h-3.5 text-zinc-500" />
                <select value={filterSystem} onChange={(e) => setFilterSystem(e.target.value)} className="bg-zinc-900 border border-zinc-700 rounded-md text-xs text-zinc-300 px-2 py-1.5 outline-none cursor-pointer min-w-[100px]">
                  <option value="">All Systems</option>
                  {allSystems.map((s) => <option key={s} value={s}>{s}</option>)}
                </select>
                <select value={filterMission} onChange={(e) => setFilterMission(e.target.value)} className="bg-zinc-900 border border-zinc-700 rounded-md text-xs text-zinc-300 px-2 py-1.5 outline-none cursor-pointer min-w-[100px]">
                  <option value="">All Missions</option>
                  {allMissions.map((m) => <option key={m} value={m}>{m}</option>)}
                </select>
                {(filterSystem || filterMission) && (
                  <button onClick={() => { setFilterSystem(""); setFilterMission(""); }} className="text-[10px] text-zinc-400 hover:text-zinc-200 cursor-pointer transition-colors underline">Clear</button>
                )}
              </div>
            </div>
          </CardHeader>
          <CardContent>
            {filteredOutcomes.length === 0 ? (
              <p className="text-sm text-zinc-500 text-center py-8">No outcomes found for the selected filters.</p>
            ) : (
              <div className="space-y-2 max-h-[400px] overflow-y-auto pr-1">
                {filteredOutcomes.map((o, i) => (
                  <div key={`${o.date}-${i}`} className="flex items-start gap-3 p-3 rounded-lg bg-zinc-950 border border-zinc-800 hover:border-zinc-700 transition-colors group">
                    <div className={`w-2 h-2 rounded-full mt-1.5 shrink-0 ${o.completed ? "bg-emerald-500" : "bg-zinc-600"}`} />
                    <div className="flex-1 min-w-0 space-y-1">
                      <p className="text-sm text-zinc-200 font-medium">{o.task || "Untitled task"}</p>
                      {o.outcome && <p className="text-xs text-zinc-400"><span className="text-zinc-500">Outcome:</span> {o.outcome}</p>}
                      <div className="flex items-center gap-2 flex-wrap">
                        {o.system && <span className="text-[10px] px-1.5 py-0.5 rounded bg-blue-500/10 text-blue-400 font-medium">{o.system}</span>}
                        {o.mission && <span className="text-[10px] px-1.5 py-0.5 rounded bg-purple-500/10 text-purple-400 font-medium">{o.mission}</span>}
                        <span className="text-[10px] text-zinc-500 ml-auto">{getShortDate(o.date)}</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </>)}
    </div>
  );
}
