import { useState, useCallback } from "react";
import { Plus, Trash2, Calendar, Brain, Heart, ChevronLeft, ChevronRight, CheckCircle2, Download } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import { useData } from "@/contexts/DataContext";
import type { DailyEntry, Task, MentalRating, PhysicalStatus } from "@/types";

function getDateString(d: Date) { return d.toISOString().split("T")[0]; }
function formatDate(d: Date) { return d.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" }); }
function formatDateLong(d: Date) { return d.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" }); }

function createEmptyEntry(date: string): DailyEntry {
  return { id: Date.now().toString() + Math.random().toString(36).substr(2, 9), date, tasks: [], mentalStatus: { morning: 2, afternoon: 2, night: 2 }, physicalStatus: "good", physicalNote: "", mentalNote: "", journal: "", bestThing: "", proudThings: "", lessonLearned: "", lessonChange: "", excitedAbout: "" };
}
function createEmptyTask(): Task {
  return { id: Date.now().toString() + Math.random().toString(36).substr(2, 9), task: "", outcome: "", system: "", mission: "", completed: false };
}

function mentalLabel(v: number) { return v === 1 ? "Low" : v === 2 ? "Medium" : "High"; }

function generateMarkdown(entry: DailyEntry, date: Date): string {
  const lines: string[] = [];
  lines.push(`# Daily Journal — ${formatDateLong(date)}`);
  lines.push("");

  // Tasks
  lines.push("## Tasks");
  lines.push("");
  if (entry.tasks.length === 0) {
    lines.push("_No tasks recorded._");
  } else {
    for (const t of entry.tasks) {
      if (!t.task.trim()) continue;
      const check = t.completed ? "x" : " ";
      lines.push(`- [${check}] **${t.task}**`);
      if (t.outcome.trim()) lines.push(`  - **Outcome:** ${t.outcome}`);
      if (t.system.trim()) lines.push(`  - **System:** ${t.system}`);
      if (t.mission.trim()) lines.push(`  - **Mission:** ${t.mission}`);
    }
    const done = entry.tasks.filter((t) => t.completed).length;
    lines.push("");
    lines.push(`> **Completion:** ${done}/${entry.tasks.length} (${entry.tasks.length > 0 ? Math.round((done / entry.tasks.length) * 100) : 0}%)`);
  }
  lines.push("");

  // Mental Status
  lines.push("## Mental Status");
  lines.push("");
  lines.push(`| Period    | Rating |`);
  lines.push(`|-----------|--------|`);
  lines.push(`| Morning   | ${mentalLabel(entry.mentalStatus.morning)} (${entry.mentalStatus.morning}/3) |`);
  lines.push(`| Afternoon | ${mentalLabel(entry.mentalStatus.afternoon)} (${entry.mentalStatus.afternoon}/3) |`);
  lines.push(`| Night     | ${mentalLabel(entry.mentalStatus.night)} (${entry.mentalStatus.night}/3) |`);
  if (entry.mentalNote.trim()) {
    lines.push("");
    lines.push(`**Note:** ${entry.mentalNote}`);
  }
  lines.push("");

  // Physical Status
  lines.push("## Physical Status");
  lines.push("");
  lines.push(`**Status:** ${entry.physicalStatus.charAt(0).toUpperCase() + entry.physicalStatus.slice(1)}`);
  if (entry.physicalNote.trim()) {
    lines.push("");
    lines.push(`**Note:** ${entry.physicalNote}`);
  }
  lines.push("");

  // Journal
  if (entry.journal.trim()) {
    lines.push("## Journal");
    lines.push("");
    lines.push(entry.journal);
    lines.push("");
  }

  // Reflective Questions
  if (entry.bestThing.trim() || entry.proudThings.trim() || entry.lessonLearned.trim() || entry.lessonChange.trim() || entry.excitedAbout.trim()) {
    lines.push("## Reflective Questions");
    lines.push("");
    if (entry.bestThing.trim()) {
      lines.push(`**What is the best thing that happened today?** ${entry.bestThing}`);
      lines.push("");
    }
    if (entry.proudThings.trim()) {
      lines.push(`**What things make you proud today?** ${entry.proudThings}`);
      lines.push("");
    }
    if (entry.lessonLearned.trim()) {
      lines.push(`**What lesson did I learn today?** ${entry.lessonLearned}`);
      lines.push("");
    }
    if (entry.lessonChange.trim()) {
      lines.push(`**What will be changed by this lesson?** ${entry.lessonChange}`);
      lines.push("");
    }
    if (entry.excitedAbout.trim()) {
      lines.push(`**What makes you excited today?** ${entry.excitedAbout}`);
      lines.push("");
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`_Generated by Daily Tracker on ${new Date().toLocaleString()}_`);
  return lines.join("\n");
}

function downloadMd(content: string, filename: string) {
  try {
    const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 100);
  } catch (error) {
    console.error("Error in downloadMd:", error);
    throw error;
  }
}

export function JournalPage() {
  const [currentDate, setCurrentDate] = useState(new Date());
  const dateKey = getDateString(currentDate);
  const { entries, updateEntry } = useData();
  const entry = entries[dateKey] || createEmptyEntry(dateKey);

  const save = useCallback((updates: Partial<DailyEntry>) => {
    updateEntry(dateKey, { ...entry, ...updates });
  }, [dateKey, entry, updateEntry]);

  const addTask = () => save({ tasks: [...entry.tasks, createEmptyTask()] });
  const updateTask = (id: string, field: keyof Task, value: string | boolean) => {
    save({ tasks: entry.tasks.map((t) => t.id === id ? { ...t, [field]: value } : t) });
  };
  const removeTask = (id: string) => save({ tasks: entry.tasks.filter((t) => t.id !== id) });

  const goToPrevDay = () => { const d = new Date(currentDate); d.setDate(d.getDate() - 1); setCurrentDate(d); };
  const goToNextDay = () => { const d = new Date(currentDate); d.setDate(d.getDate() + 1); setCurrentDate(d); };
  const goToToday = () => setCurrentDate(new Date());
  const isToday = dateKey === getDateString(new Date());

  const handleDownloadMd = () => {
    try {
      const md = generateMarkdown(entry, currentDate);
      if (!md || md.trim() === "") {
        alert("No content to export. Please add some data to your journal first.");
        return;
      }
      downloadMd(md, `journal-${dateKey}.md`);
    } catch (error) {
      console.error("Error exporting markdown:", error);
      alert("Error exporting markdown file. Please try again.");
    }
  };

  return (
    <div className="fade-in space-y-5">
      {/* Date Navigation */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-zinc-100 tracking-tight">Journal</h2>
          <p className="text-sm text-zinc-400 mt-0.5">Record your day, track your progress</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={handleDownloadMd} className="gap-1.5 text-xs h-8 border-zinc-700 text-zinc-300 hover:text-white">
            <Download className="w-3.5 h-3.5" />Export .md
          </Button>
          <Button variant="ghost" size="icon" onClick={goToPrevDay}><ChevronLeft className="w-4 h-4" /></Button>
          <Button variant={isToday ? "default" : "outline"} size="sm" onClick={goToToday} className="min-w-[140px] gap-2">
            <Calendar className="w-3.5 h-3.5" />{formatDate(currentDate)}
          </Button>
          <Button variant="ghost" size="icon" onClick={goToNextDay}><ChevronRight className="w-4 h-4" /></Button>
        </div>
      </div>

      {/* Tasks */}
      <Card className="glow-blue-subtle">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2.5">
              <div className="w-7 h-7 rounded-lg bg-blue-500/10 flex items-center justify-center"><CheckCircle2 className="w-4 h-4 text-blue-400" /></div>
              <span className="text-zinc-100">Tasks</span>
            </CardTitle>
            <Button size="sm" onClick={addTask} className="h-8 gap-1.5"><Plus className="w-3.5 h-3.5" />Add Task</Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <table className="task-table">
              <thead>
                <tr>
                  <th className="w-10"></th>
                  <th>Task</th>
                  <th>Expected Outcome</th>
                  <th>System</th>
                  <th>Mission</th>
                  <th className="w-12"></th>
                </tr>
              </thead>
              <tbody>
                {entry.tasks.length === 0 && (
                  <tr><td colSpan={6} className="text-center text-zinc-500 text-sm py-8">No tasks yet. Click "Add Task" to start.</td></tr>
                )}
                {entry.tasks.map((t) => (
                  <tr key={t.id} className={`group ${t.completed ? "opacity-50" : ""}`}>
                    <td className="text-center">
                      <button onClick={() => updateTask(t.id, "completed", !t.completed)} className={`w-5 h-5 rounded-md border-2 flex items-center justify-center transition-all ${t.completed ? "bg-blue-500 border-blue-500" : "border-zinc-600 hover:border-blue-400"}`}>
                        {t.completed && <CheckCircle2 className="w-3.5 h-3.5 text-white" />}
                      </button>
                    </td>
                    <td><Input placeholder="Task description" value={t.task} onChange={(e) => updateTask(t.id, "task", e.target.value)} className="bg-transparent border-none text-zinc-200 focus-visible:ring-1" /></td>
                    <td><Input placeholder="Expected outcome" value={t.outcome} onChange={(e) => updateTask(t.id, "outcome", e.target.value)} className="bg-transparent border-none text-zinc-200 focus-visible:ring-1" /></td>
                    <td><Input placeholder="System to follow" value={t.system} onChange={(e) => updateTask(t.id, "system", e.target.value)} className="bg-transparent border-none text-zinc-200 focus-visible:ring-1" /></td>
                    <td><Input placeholder="Mission/purpose" value={t.mission} onChange={(e) => updateTask(t.id, "mission", e.target.value)} className="bg-transparent border-none text-zinc-200 focus-visible:ring-1" /></td>
                    <td className="text-center">
                      <button onClick={() => removeTask(t.id)} className="opacity-0 group-hover:opacity-100 transition-opacity text-slate-500 hover:text-red-400"><Trash2 className="w-4 h-4" /></button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Mental Status */}
        <Card className="glow-blue-subtle">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2.5">
              <div className="w-7 h-7 rounded-lg bg-purple-500/10 flex items-center justify-center"><Brain className="w-4 h-4 text-purple-400" /></div>
              <span className="text-zinc-100">Mental Status</span>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {(["morning", "afternoon", "night"] as const).map((period) => (
              <div key={period}>
                <span className="text-xs font-medium text-zinc-400 capitalize block mb-2">{period}</span>
                <RadioGroup
                  value={String(entry.mentalStatus[period])}
                  onValueChange={(v: string) => save({ mentalStatus: { ...entry.mentalStatus, [period]: parseInt(v) as MentalRating } })}
                  className="flex items-center gap-2"
                >
                  <span className="text-[10px] text-zinc-500 font-medium w-6">Low</span>
                  <RadioGroupItem value="1" id={`mental-${period}-1`} />
                  <RadioGroupItem value="2" id={`mental-${period}-2`} />
                  <RadioGroupItem value="3" id={`mental-${period}-3`} />
                  <span className="text-[10px] text-zinc-500 font-medium w-8">High</span>
                </RadioGroup>
              </div>
            ))}
            <Separator className="bg-zinc-700/50" />
            <div>
              <Label className="text-xs text-zinc-400">Note</Label>
              <Input placeholder="Any notes about your mental state..." value={entry.mentalNote} onChange={(e) => save({ mentalNote: e.target.value })} className="mt-1.5 h-9 text-xs bg-zinc-900 border-zinc-700 text-zinc-200 placeholder:text-zinc-600" />
            </div>
          </CardContent>
        </Card>

        {/* Physical Status */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2.5">
              <div className="w-7 h-7 rounded-lg bg-emerald-500/10 flex items-center justify-center"><Heart className="w-4 h-4 text-emerald-400" /></div>
              <span className="text-zinc-100">Physical</span>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <RadioGroup value={entry.physicalStatus} onValueChange={(v: string) => save({ physicalStatus: v as PhysicalStatus })} className="space-y-2.5">
              {([{ value: "good", label: "Good" }, { value: "sick", label: "Sick" }, { value: "critical", label: "Critical" }] as const).map((item) => (
                <div key={item.value} className="flex items-center gap-2.5">
                  <RadioGroupItem value={item.value} id={`physical-${item.value}`} />
                  <Label htmlFor={`physical-${item.value}`} className="cursor-pointer text-sm text-zinc-300">{item.label}</Label>
                </div>
              ))}
            </RadioGroup>
            <Separator className="my-2 bg-zinc-700/50" />
            <div>
              <Label className="text-xs text-zinc-400">Note</Label>
              <Input placeholder="Any notes about your physical state..." value={entry.physicalNote} onChange={(e) => save({ physicalNote: e.target.value })} className="mt-1.5 h-9 text-xs bg-zinc-900 border-zinc-700 text-zinc-200 placeholder:text-zinc-600" />
            </div>
          </CardContent>
        </Card>

        {/* Quick Stats */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2.5">
              <div className="w-7 h-7 rounded-lg bg-blue-500/10 flex items-center justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-blue-400"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>
              </div>
              <span className="text-zinc-100">Stats</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              <div className="flex justify-between items-center">
                <span className="text-xs text-zinc-400">Total Tasks</span>
                <span className="text-sm font-bold text-blue-400">{entry.tasks.length}</span>
              </div>
              <Separator className="bg-zinc-700/50" />
              <div className="flex justify-between items-center">
                <span className="text-xs text-zinc-400">Completed</span>
                <span className="text-sm font-bold text-emerald-400">{entry.tasks.filter((t) => t.completed).length}</span>
              </div>
              </div>
              <Separator className="bg-zinc-700/50" />
              <div className="flex justify-between items-center">
                <span className="text-xs text-zinc-400">Completion</span>
                <span className="text-sm font-bold text-purple-400">{entry.tasks.length > 0 ? Math.round((entry.tasks.filter((t) => t.completed).length / entry.tasks.length) * 100) : 0}%</span>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Journal */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-blue-500/10 flex items-center justify-center">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-blue-400"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>
            </div>
            <span className="text-slate-100">Journal</span>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Textarea placeholder="Write about your day... What happened? What did you learn? How do you feel?" value={entry.journal} onChange={(e) => save({ journal: e.target.value })} className="min-h-[200px] text-sm leading-relaxed bg-zinc-900 border-zinc-700 text-zinc-200 placeholder:text-zinc-600" />
        </CardContent>
      </Card>

      {/* Reflective Questions */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-purple-500/10 flex items-center justify-center"><CheckCircle2 className="w-4 h-4 text-purple-400" /></div>
            <span className="text-zinc-100">Reflective Questions</span>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <Label className="text-xs text-zinc-400">What is the best thing that happened today?</Label>
            <Input placeholder="Share the highlight of your day..." value={entry.bestThing} onChange={(e) => save({ bestThing: e.target.value })} className="mt-1.5 h-9 text-xs bg-zinc-900 border-zinc-700 text-zinc-200 placeholder:text-zinc-600" />
          </div>
          <div>
            <Label className="text-xs text-zinc-400">What things make you proud today?</Label>
            <Input placeholder="What accomplishments or qualities are you proud of?" value={entry.proudThings} onChange={(e) => save({ proudThings: e.target.value })} className="mt-1.5 h-9 text-xs bg-zinc-900 border-zinc-700 text-zinc-200 placeholder:text-zinc-600" />
          </div>
          <div>
            <Label className="text-xs text-zinc-400">What lesson did I learn today?</Label>
            <Input placeholder="What did you learn from your experiences today?" value={entry.lessonLearned} onChange={(e) => save({ lessonLearned: e.target.value })} className="mt-1.5 h-9 text-xs bg-zinc-900 border-zinc-700 text-zinc-200 placeholder:text-zinc-600" />
          </div>
          <div>
            <Label className="text-xs text-zinc-400">What will be changed by this lesson?</Label>
            <Input placeholder="How will this lesson change your behavior or decisions going forward?" value={entry.lessonChange} onChange={(e) => save({ lessonChange: e.target.value })} className="mt-1.5 h-9 text-xs bg-zinc-900 border-zinc-700 text-zinc-200 placeholder:text-zinc-600" />
          </div>
          <div>
            <Label className="text-xs text-zinc-400">What makes you excited today?</Label>
            <Input placeholder="What are you looking forward to or feeling excited about?" value={entry.excitedAbout} onChange={(e) => save({ excitedAbout: e.target.value })} className="mt-1.5 h-9 text-xs bg-zinc-900 border-zinc-700 text-zinc-200 placeholder:text-zinc-600" />
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
